version: "3.9"
services:
  frontend:
    container_name: ntnureads_frontend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      # Context specifies where we pull the files/folder from
      context: .
      dockerfile: Dockerfile.dev
    # Map local port to container port
    ports:
      - "3000:3000"
    volumes:
      # Put bookmark/placeholder on the node_modules folder inside the container
      - /usr/src/app/node_modules
      - .:/usr/src/app
  backend:
    container_name: ntnureads_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
    - "4000:4000"
    volumes:
      - /usr/src/app/node_modules
      # To not map the local backend folder to container
      - ./backend:/usr/src/app
    environment:
      # Make sure backend is hot reloaded (windows problem)
      CHOKIDAR_USEPOLLING: "true"
