describe('Login', () => {
    before(() => {
        cy.visit('/login')
    })
    beforeEach(() => {
        cy.visit('/')
    })
    it('user can log in', () => {
        cy.get('Nav').children().contains("Logg inn/ut")
            .click()
            .get("Form")
            .get("input[type='username'")
            .type("willi1")
            .get("input[type='checkbox']").check()
            .get("input[type='password'")
            .type("willi123")
            .type("{enter}")
            .window()
            .its("sessionStorage")
            .invoke("getItem", "user")
            .should("exist")
    })
    it('user can log out', () => {
        cy.get('Nav').children().contains("Logg inn/ut")
            .click()
            .window()
            .its("sessionStorage")
            .invoke("getItem", "user")
            .should("not.exist")
    })
    it('user can to profile page', () => {
        cy.get('Nav').children().contains("Logg inn/ut")
            .click()
            .get("Form")
            .get("input[type='username']")
            .type("willi1")
            .get("input[type='checkbox']").check()
            .get("input[type='password'")
            .type("willi123")
            .type("{enter}")
            .get('Nav').children().contains("Profil")
            .click()
            .url().should("eq","http://localhost:3000/profile")
    })
    it('cannot log in to unregistrered user',() => {
        cy.get('Nav').children().contains("Logg inn/ut")
            .click()
            .click()
            .get("Form")
            .get("input[type='username']")
            .type("jksdbfkjshfuk")
            .get("input[type='checkbox']").check()
            .get("input[type='password'")
            .type("sebfkhjeagfjeg")
            .type("{enter}")
            .window()
            .its("sessionStorage")
            .invoke("getItem", "user")
            .should("not.exist")
            .url().should("eq","http://localhost:3000/login")
    })
})